In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
# creating the array

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# dimensions of the array

print(arr.ndim)

2


In [6]:
# shape of the array

print(arr.shape)

(2, 4)


In [7]:
print(type(arr))


<class 'numpy.ndarray'>


In [9]:
print(arr.data)

In [ ]:
# In 2-d array

# axis = 0 (column)
# axis = 1 (row)


In [10]:
arr2 = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(arr2)
# or print(arr2,"\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]]


In [11]:
arr2.dtype

dtype('int32')

In [12]:
arr2.itemsize

4

In [13]:
# elements in a
arr2.size

9

In [14]:
arr2.shape

(3, 3)

In [4]:
arr3 = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.float64)
print(arr3,"\n")
print(arr3.dtype,"\n")
print(arr3.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [5]:
arr3 = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.float32)
print(arr3,"\n")
print(arr3.dtype,"\n")
print(arr3.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float32 

4


In [6]:
arr3 = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.float)
print(arr3,"\n")
print(arr3.dtype,"\n")
print(arr3.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


C:\Users\SAP\AppData\Local\Temp\ipykernel_12640\790133741.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr3 = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.float)


In [7]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.complex128)

print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize,"\n")

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16 



In [8]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.complex32)


AttributeError: module 'numpy' has no attribute 'complex32'

In [9]:
# sum elements in array
print(np.sum(arr3))

234.0


In [14]:
# sum valued along a specified axis
print(arr3,"\n")
# for columns
print(np.sum(arr3,axis=0),"\n")
# for rows
print(np.sum(arr3,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[75. 78. 81.] 

[63. 78. 93.]


In [19]:
# minimum value (in previous versions amin was working here min is also working)
print(np.min(arr3),"\n")
# for columns
print(np.min(arr3,axis=0))
# for rows
print(np.min(arr3,axis=1))
print(type(arr3))

20.0 

[20. 21. 22.]
[20. 25. 30.]
<class 'numpy.ndarray'>


In [20]:
# Maximum values

print(np.max(arr3),"\n")
# for columns
print(np.max(arr3,axis=0))
# for rows
print(np.max(arr3,axis=1))
print(type(arr3))

32.0 

[30. 31. 32.]
[22. 27. 32.]
<class 'numpy.ndarray'>


In [21]:
# Mean
print(np.mean(arr3),"\n")
# for columns
print(np.mean(arr3,axis=0))
# for rows
print(np.mean(arr3,axis=1))
print(type(arr3))

26.0 

[25. 26. 27.]
[21. 26. 31.]
<class 'numpy.ndarray'>


In [25]:
# Median
print(arr3)
print(np.mean(arr3),"\n")
# for columns
print(np.mean(arr3,axis=0))
# for rows
print(np.mean(arr3,axis=1))
print(type(arr3))

In [26]:
# Standard deviation
print(arr3)
print(np.std(arr3),"\n")
# for columns
print(np.std(arr3,axis=0))
# for rows
print(np.std(arr3,axis=1))
print(type(arr3))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]
4.163331998932265 

[4.0824829 4.0824829 4.0824829]
[0.81649658 0.81649658 0.81649658]
<class 'numpy.ndarray'>


In [28]:
# variance

print(arr3)
print(np.var(arr3))
print(np.var(arr3,axis=0))
print(np.var(arr3,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]
17.333333333333332
[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]


In [31]:
# covariance

print(arr3)
print(np.cov(arr3))
# print(np.cov(arr3,axis=0))
# print(np.cov(arr3,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# weighted average
print(np.average(arr3))

26.0


In [32]:
c = np.array([2,4,6,8,10,12,14,7,11])
print(c)

[ 2  4  6  8 10 12 14  7 11]


In [35]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25]


In [36]:
print(np.average(c,weights=weight))

8.076923076923077


In [38]:
# percentile
print(c,"\n")

print(np.percentile(c,5,0)) #percentile of first 5 columns as 0 is mentioned
print(np.percentile(c,8,0))
print(np.percentile(arr3,5,1))
print(np.percentile(arr3,5,0))
print(np.percentile(arr3,4,0))
print(np.percentile(arr3,4,1))

[ 2  4  6  8 10 12 14  7 11] 

2.8
3.2800000000000002
[20.1 25.1 30.1]
[20.5 21.5 22.5]
[20.4 21.4 22.4]
[20.08 25.08 30.08]


In [39]:
# peak to peak (maximum - minimum)

print(arr3,"\n")
print(c,"\n")

print(np.ptp(c,0))
print(np.ptp(arr3,0))
print(np.ptp(arr3,1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[ 2  4  6  8 10 12 14  7 11] 

12
[10. 10. 10.]
[2. 2. 2.]


In [42]:
print(arr3)
print(arr3.shape,"\n")
print(arr3.reshape(1,9),"\n")
print(arr3)


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]
(3, 3) 

[[20. 21. 22. 25. 26. 27. 30. 31. 32.]] 

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]


In [45]:
b = np.array([[5656,1155],[1561,153654],[4418,8485],[6146,4113]])
print(b)

[[  5656   1155]
 [  1561 153654]
 [  4418   8485]
 [  6146   4113]]


In [46]:
print(b.reshape(2,4))

[[  5656   1155   1561 153654]
 [  4418   8485   6146   4113]]


In [47]:
e = [20,48,96,57,36,14,63]
print(e[:])
print(e[1:])
print(e[:4])
print(e[-1])

[20, 48, 96, 57, 36, 14, 63]
[48, 96, 57, 36, 14, 63]
[20, 48, 96, 57]
63


In [54]:
# 2d array

l = np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[0:2,1],"\n")
print(f"Value of l[-1] is{l[-1]} :","\n")
print(l[-1,0:2],"\n")
print(l[-2,0:2],"\n")
print(l[-2,2],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

[25 45] 

Value of l[-1] is[62 66 68 70] : 

[62 66] 

[43 45] 

47 



In [2]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12,24).reshape(3,4)
print(f,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



In [3]:
# horizontal stacking (It will merge arrays horizontally)

print(np.hstack((d,f)),'\n')
print(np.hstack((f,d)),'\n')

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [4]:
# verticAL STACKING (it will merge array vertically)

print(np.vstack((d,f)),'\n')
print(np.vstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [5]:
# MAthematical operations

x = np.array([2,8,10,3,55,60])
y = np.array([1,7,9,34,54,59])

print(x)
print(y)
print(x+y,"\n")
print(x*y,"\n")
print(x-y,"\n")
print(x/y,"\n")
print(x//y,"\n")

[ 2  8 10  3 55 60]
[ 1  7  9 34 54 59]
[  3  15  19  37 109 119] 

[   2   56   90  102 2970 3540] 

[  1   1   1 -31   1   1] 

[2.         1.14285714 1.11111111 0.08823529 1.01851852 1.01694915] 

[2 1 1 0 1 1] 



In [ ]:
print(np.zeros((4,3)),"\n")

In [1]:
import numpy as np

In [4]:
# RANDOM NUMBE4RS IN NUMPY

from numpy import random
x=random.randint(100)
print(x)

52


In [5]:

#  GENERATING RANDOM FLOAT NUMBER

x = random.rand(10)
print(x)

[0.77714613 0.42975132 0.57848849 0.17169085 0.04688939 0.68809993
 0.39063669 0.18878445 0.73659869 0.92619265]


In [7]:
# GENERATING RANDOM ARRAY

x = random.randint(100,size=(15))
print(x)

[11 18 49 97 45 22 34 83  8 96 37 85  5 85 72]


In [8]:
# GENERATING RANDOM MATRIX(2 - D array) each row containing 4 random numbers from 0 to 100

x= random.randint(100,size=(3,4))
print(x)

[[97 26 66 63]
 [34 87 16 73]
 [ 5 58 47 83]]


In [11]:
# CREATING SCALAR USING NUMPY

in_arr = np.array([8])
print("Input array is ",in_arr)

out_scalar = np.asscalar(in_arr)
print("Output scalar from input array ",out_scalar)

Input array is  [8]
Output scalar from input array  8


C:\Users\SAP\AppData\Local\Temp\ipykernel_9004\3325819600.py:6: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


In [12]:
# CREATING VECTOR 

list1 = [1,2,3]

list2=[[10],
      [20],
      [30]]

# create vector
vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("<!-------------------------------------------------!>")

print("Vertical Vector")
print(vector2)


Horizontal Vector
[1 2 3]
<!-------------------------------------------------!>
Vertical Vector
[[10]
 [20]
 [30]]


In [14]:
# creating matrix

import numpy as np

a= np.matrix('1,2;3,4')
print("via array-like input:\n",a,"\n")

# array like input
b= np.matrix([[5,6,7],[4,6]])
print("via array-like input:\n",b,"\n")



via array-like input:
 [[1 2]
 [3 4]] 

via array-like input:
 [[list([5, 6, 7]) list([4, 6])]] 



C:\Users\SAP\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [15]:
#  MATRIX MULTIPLICATION

A = 5
B = [[6,7],[8,9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [19]:
A = [[6,7],[8,9]]

B = [[1,3],[5,7]]
print("Dot Product Of A and B ",np.dot(A,B))

print("\n")

print("Dot Product of B and A",np.dot(B,A))

Dot Product Of A and B  [[41 67]
 [53 87]]


Dot Product of B and A [[30 34]
 [86 98]]


In [ ]:
# Measure of Central Tendency

In [22]:
data = [32,36,46,47,56,69,75,79,79,88,89,91,92,93,96,97,101,105,112,116]

# first quartile
Q1 = np.median(data[:10])
print(data[:10])

# third quartile
Q3 = np.median(data[10:])

# interquartile range
IQR = Q3-Q1
print(IQR)

[32, 36, 46, 47, 56, 69, 75, 79, 79, 88]
34.0


In [23]:
# Array Broadcasting

a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

a*b


array([2., 4., 6.])

In [24]:
a = np.array([1.0,2.0,3.0])\
b = 5.0

a*b

SyntaxError: invalid syntax (430368099.py, line 2)